spring:
  application:
    name: challenge
  datasource:
    url: ${DB_URL}
    hikari:
      schema: ${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${DB_DEFAULT_SCHEMA}
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: /db/changelog/liquibase-changelog.xml
    liquibase-schema: challenge

  cache:
    type: caffeine
    caffeine:
      spec:
        maximumSize: 100

logging:
  level:
    org:
      springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: "health,info"